menu:
#- {name: 'lab', url: '/lab'}
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'talks', url: '/talks'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#lab:

people:
- {name: 'Chih-Yuan Yang 楊智淵', title: 'Assistant Professor', description: 'Expertise in computer vision and stock investing', department: 'Artificial Intelligence', institution: 'Chang Gung University', institution_address: 'No.259, Wenhua 1st Rd., Guishan Dist., Taoyuan City 33302, Taiwan (R.O.C.).', phone: '+886-3-2118800 #2543', email: 'cyyang@cgu.edu.tw', office: 'Management Building Room 1416', image: 'assets/img/cyyang20241018.jpg', url: 'Chih-Yuan_Yang'}
#master_student:
- {name: 'Brian Liu 劉冠亨', title: "Master's student" , image: 'assets/img/Brian_Liu.jpg', description: 'Expertise in electronic engineering', url: 'Brian_Liu'}
- {name: 'Wayne Tsai 蔡承原', title: "Master's student" , image: 'assets/img/Wayne_Tsai.jpg', description: 'Intereted in medical images', url: 'Wayne_Tsai'}
- {name: 'Eric Lu 盧睿霆', title: "Master's student" , image: 'assets/img/Eric_Lu.png', description: 'Intereted in facial expression recognition', url: 'Eric_Lu'}
#capstone_student:
- {name: 'Matt Wu 吳奕廷', title: 'Capstone student' , image: 'assets/img/Matt_Wu.png', description: 'AI program student', url: 'Matt_Wu'}
- {name: 'Eric Chen 陳毅', title: 'Capstone student' , image: '', description: 'AI program student', url: 'Eric_Chen'}

courses:
- {name: '生成式AI：文字與圖像生成的原理與實務 (Generative AI: Text and Image Synthesis Principles and Practice) 2025', url: 'GenerativeAI2025'}
- {name: 'Survey of Intelligent Technologies 2024', url: 'SurveyOfIntelligentTechnologies2024'}
- {name: 'Computer Vision 2024', url: 'cv2024'}
- {name: '機器學習 (Machine Learning) 2024', url: 'MachineLearning2024'}
- {name: '人工智慧概論 (Introduction to AI) 2024 (醫學系A Medicine School A)', url: 'IntroToAI2024_medicine_A'}
- {name: '人工智慧概論 (Introduction to AI) 2024 (職治系 Occupational Therapy Department)', url: 'IntroToAI2024_occupational_therapy'}
- {name: '健康應用之程式語言 (Programming Design for Health Applications) 2024 (呼治系 Respiratory Therapy Department)', url: 'HealthLanguage2024_respiratory_therapy'}
- {name: '健康應用之程式語言 (Programming Design for Health Applications) 2024 (物治系 Physical Therapy Department)', url: 'HealthLanguage2024_physical_therapy'}
- {name: 'Computer Vision 2023', url: 'cv2023'}

talks:
- {name: 'Stock Investing at NTU iAgent lab', url: 'stock_investing_2303'}

social:
- {icon: 'github', link: 'https://github.com/yangchihyuan'}

contacts:
- {name: 'Chih-Yuan Yang Ph.D.', title: 'Assistant Professor', department: 'Artificial Intelligence', institution: 'Chang Gung University', institution_address: 'No. 259, Wenhua 1st Rd., Guishan Dist., Taoyuan City 33302, Taiwan (R.O.C.).', phone: '+886-3-2118800 #2548', email: 'cyyang@cgu.edu.tw', office: 'Management Building B1416', image: 'assets/img/cyyang20241018.jpg'}
